version: '3.8'

services:
  # Laravel приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dobrenok_blog_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
    env_file:
      - .env
    networks:
      - dobrenok_network
    depends_on:
      - nginx

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: dobrenok_blog_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - dobrenok_network

networks:
  dobrenok_network:
    driver: bridge
